#!/bin/bash

tty=
tty -s && tty=--tty
docker run \
    $tty \
    --interactive \
    --rm \
    --volume /etc/passwd:/etc/passwd:ro \
    --volume /etc/group:/etc/group:ro \
    --network host \
    jonahgeorge/vsql "$@"
