#!/bin/bash

tty=
tty -s && tty=--tty
docker run \
    $tty \
    --interactive \
    --rm \
    --user $(id -u):$(id -g) \
    --volume /etc/passwd:/etc/passwd:ro \
    --volume /etc/group:/etc/group:ro \
    --volume $(pwd):/app \
    jonahgeorge/schema-tool "$@"
